BBVA_RUBRO_MAP = {
    3: "gastronomia",
    4: "entretenimiento",
    8: "cuidado_personal",
    13: "turismo",
    26: "supermercados",
    170: "moda",
    173: "hogar",
    174: "automotores",
    175: "infantil",
    184: "deportes",
    192: "tecnologia",
    195: "bazar",
}

SANTANDER_CAT_MAP = {
    "GAS": "gastronomia",
    "DIN": "gastronomia",
    "ESP": "entretenimiento",
    "FAR": "cuidado_personal",
    "PELU": "cuidado_personal",
    "PER": "cuidado_personal",
    "CPE": "cuidado_personal",
    "VIA": "turismo",
    "SUP": "supermercados",
    "IND": "moda",
    "HOG": "hogar",
    "AUT": "automotores",
    "JUG": "infantil",
    "DEP": "deportes",
    "EDU": "deportes",
    "VAR": "bazar",
    "LIB": "libros",
    "MOD": "modo_digital",
    "SEC": "select",
    "SMI": "super_miercoles",
    "SOR": "sorpresa",
}

CANONICAL_CATEGORIES = [
    {
        "canonical_key": "gastronomia",
        "display_name_es": "Gastronomía y Restoranes",
        "icon_emoji": "🍽️",
        "bbva_rubros": [3],
        "santander_categories": ["GAS", "DIN"],
    },
    {
        "canonical_key": "entretenimiento",
        "display_name_es": "Entretenimiento y Espectáculos",
        "icon_emoji": "🎭",
        "bbva_rubros": [4],
        "santander_categories": ["ESP"],
    },
    {
        "canonical_key": "cuidado_personal",
        "display_name_es": "Cuidado Personal y Farmacias",
        "icon_emoji": "💊",
        "bbva_rubros": [8],
        "santander_categories": ["FAR", "PELU", "PER", "CPE"],
    },
    {
        "canonical_key": "turismo",
        "display_name_es": "Viajes y Turismo",
        "icon_emoji": "✈️",
        "bbva_rubros": [13],
        "santander_categories": ["VIA"],
    },
    {
        "canonical_key": "supermercados",
        "display_name_es": "Supermercados",
        "icon_emoji": "🛒",
        "bbva_rubros": [26],
        "santander_categories": ["SUP"],
    },
    {
        "canonical_key": "moda",
        "display_name_es": "Moda e Indumentaria",
        "icon_emoji": "👗",
        "bbva_rubros": [170],
        "santander_categories": ["IND"],
    },
    {
        "canonical_key": "hogar",
        "display_name_es": "Hogar y Decoración",
        "icon_emoji": "🏠",
        "bbva_rubros": [173],
        "santander_categories": ["HOG"],
    },
    {
        "canonical_key": "automotores",
        "display_name_es": "Automotores y Servicios",
        "icon_emoji": "🚗",
        "bbva_rubros": [174],
        "santander_categories": ["AUT"],
    },
    {
        "canonical_key": "infantil",
        "display_name_es": "Jugueterías e Infantiles",
        "icon_emoji": "🧸",
        "bbva_rubros": [175],
        "santander_categories": ["JUG"],
    },
    {
        "canonical_key": "deportes",
        "display_name_es": "Deportes y Educación",
        "icon_emoji": "🏋️",
        "bbva_rubros": [184],
        "santander_categories": ["DEP", "EDU"],
    },
    {
        "canonical_key": "tecnologia",
        "display_name_es": "Electro y Tecnología",
        "icon_emoji": "📱",
        "bbva_rubros": [192],
        "santander_categories": [],
    },
    {
        "canonical_key": "bazar",
        "display_name_es": "Bazar, Regalos y Vinos",
        "icon_emoji": "🎁",
        "bbva_rubros": [195],
        "santander_categories": ["VAR"],
    },
    {
        "canonical_key": "libros",
        "display_name_es": "Librerías y Cultura",
        "icon_emoji": "📚",
        "bbva_rubros": [],
        "santander_categories": ["LIB"],
    },
]
